### ISSUE TITLE
配置参数的小问题

### ISSUE THREAD

**Issue by LL1024LL** [shimohq/mogo#100]
https://github.com/shimohq/mogo/blob/2add14e0e2311d84bc5edfe43de57452c2f61ec3/data/all-in-one/mogo/config/docker.toml#L71

writer_timeou 少了个字符't'

**Comment by kl7sn** [comment]
感谢反馈，本次提交已修复该问题。
https://github.com/shimohq/mogo/commit/e6a733cd73c1f7811005afd63315f5567a911acb
