### ISSUE TITLE
查询25g数据表，系统直接挂了

### ISSUE THREAD

**Issue by hu-jiawen-git** [shimohq/mogo#105]
测试系统查询性能时，查询一个表25g数据
message like '%Type%'
 点击查询 查不到数据
 再次访问页面时 页面无法访问
 查看服务器 进程不在了。
 日志：
 
2022/03/24 17:47:13 code: 241, message: Memory limit (total) exceeded: would use 27.57 GiB (attempt to allocate chunk of 5769656 bytes), maximum: 27.56 GiB: (while reading column message): (while reading from part /clickhouse/data/data/store/abc/abcff6a4-e6ed-4ce0-abcf-f6a4e6ed1ce0/1648112400_62943_65222_10/ from mark 5029 with max_rows_to_read = 8192): While executing MergeTreeThread

**Comment by kl7sn** [comment]
修复了 clickhouse 报错导致的 mogo exit 问题。
https://github.com/shimohq/mogo/commit/7ef1516fa1d9501330860d6b28a93f8f50820109
