### ISSUE TITLE
关于日志存储到ck的问题咨询

### ISSUE THREAD

**Issue by wyfaq** [shimohq/mogo#109]
我看了ck中nginx的log单独存了一个字段_log_，对比了其他类似的产品发现log是json化后存不同字段的。
目前存一个字段是基于因素什么考虑的？谢谢

**Comment by kl7sn** [comment]
从可扩展性和代码复杂度上分析，在 mogo 中数据流转是 日志 -> kafka -> clickhouse kafka engine table -> materialized view table -> data table 
日志的数据结构是不确定的，简化的方案是采用 _log_ 字段统一采集日志数据，再转换到 data table 中的 _raw_log_ 字段中，如果需要将日志中的具体字段（例如 x 字段）拆分出来存储，在 data table 中新建 x 字段，配置 materialized view table 的 json 解析方法可以读取 _log_ 中的 x 字段转存到 data table 中

从成本上分析，如果不同项目的日志进行统一采集，在采集的时候反射出所有字段会增加许多冗余空值，增加不可预知性和额外开销。

综合以上两个原因，目前采用的 _log_ 字段进行完整的日志内存存储。

**Comment by wyfaq** [comment]
明白你的意思了 ，谢谢

**Comment by wyfaq** [comment]
如果log中有嵌套json，我记得ck支持的不是很好，这个是不是需要规避？filebeat采集会有这种嵌套数据

**Comment by sevennt** [comment]
举个例子，对这一条日志 `{"time":"2022-03-25 00:00:00","msg":"something wrong","data":{"name":"lee"}}`，其中的 `data` 字段实际可以解析成一个 JSON 对象。

如果只是对 `data` 建了索引，没有对 `data.name` 字段建索引，那就只能通过 like 的方式（`data like 'lee'`）来模糊搜索，查询效率不高。

但如果你对 `data.name` 建了索引，其实是可以通过 `data.name = 'lee'` 的方式来精确搜索。

**Comment by sevennt** [comment]
@wyfaq 还有其他问题么？没问题我关 issue 了。
