### ISSUE TITLE
添加clickhouse实例失败

### ISSUE THREAD

**Issue by 231bobo** [shimohq/mogo#110]
你好，在添加clickhouse的时候失败了，提示【 {"data":{"code":1,"msg":"DNS configuration exception, database connection failure: could not load time location: unknown time zone Asia/Shanghai","data":null}} 】  ，这个是什么原因？

 mogo尝试配置的数据库类型有mysql5.6、mysql5.7、tidb5.3； 
 mogo运行的方式有二进制、docker、k8s 。

**Comment by sevennt** [comment]
进到你的 Mogo 容器里面，执行 `ls -rtl /usr/share/zoneinfo/Asia/Shanghai ` 看看结果

**Comment by 231bobo** [comment]
你好 ，对应的文件不存在；时区之前已经调整为东8区了的。

/mogo # date
Mon Mar 28 11:04:21 CST 2022
/mogo # ls -rtl /usr/share/zoneinfo/Asia/Shanghai
ls: /usr/share/zoneinfo/Asia/Shanghai: No such file or directory
/mogo # 
/mogo # date
Mon Mar 28 11:05:21 CST 2022
/mogo #

**Comment by sevennt** [comment]
具体是怎么调整时区的，`apk add tzdata` 这条指令也被移除了吗？

**Comment by 231bobo** [comment]
通过映射本地的/etc/localtime路径修改的。【参考： https://www.jianshu.com/p/f56d2e174411】以下是部署使用的yaml文件内容。

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    k8s.kuboard.cn/workload: mogo
  labels:
    k8s.kuboard.cn/name: mogo
  name: mogo
  namespace: test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/name: mogo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s.kuboard.cn/name: mogo
    spec:
      containers:
      - env:
        - name: EGO_CONFIG_PATH
          value: /mogo/config/docker.toml
        - name: EGO_LOG_WRITER
          value: stderr
        image: sevennt/mogo:master
        imagePullPolicy: IfNotPresent
        lifecycle: {}
        name: mogo
        ports:
        - name: ui
          containerPort: 19001
          protocol: TCP
        resources:
          limits:
          requests:
            cpu: 10m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mogo/config/docker.toml
          name: config-volume
          subPath: docker.toml
        - mountPath: /mogo/config/resource.yaml
          name: config-volume
          subPath: resource.yaml
        - mountPath: /etc/localtime
          name: tz-config
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      nodeSelector:
        mapgoo.net/node: app
        mapgoo.net/nodetype: elastic
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        seLinuxOptions: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: mogo-cm
        name: config-volume
      - name: tz-config
        hostPath:
          path: /etc/localtime

---

**Comment by sevennt** [comment]
@231bobo 其实你部署的时候不需要通过修改 yaml 来调整时区，默认 mogo 容器已经是东八区了

**Comment by 231bobo** [comment]
你好 ， 刚刚重新确认了一次，默认不是东八区的。  

/mogo # date
Mon Mar 28 03:50:37 UTC 2022
/mogo #

**Comment by sevennt** [comment]
嗯，一会我们在 dockerfile 里面调一下，你就不用通过 yaml 来改了。

**Comment by sevennt** [comment]
拉下最新的镜像，我们已经加上了 `tzdata`，你可以通过在 yaml 里面配置 `TZ` 环境变量值为 `Asia/Shanghai` 的方式来达到修改时区的目的。

**Comment by 231bobo** [comment]
好的，我试试。

**Comment by 231bobo** [comment]
那坐等你们发布了。

**Comment by sevennt** [comment]
@231bobo 已经发布了，再测试下看看

**Comment by sevennt** [comment]
@231bobo 我先关闭了，有问题你再打开这个 issue。
