### ISSUE TITLE
import mdp/pkg/model/db

### ISSUE THREAD

**Issue by GiftLee** [shimohq/mogo#124]
api/internal/service/event/user.go 这个文件 import mdp/pkg/model/db
where  mdp/pkg/model/db
换成api/pkg/model/db  这个有过不去，userEvent.UID = opUser.Uid
代码是全的?

**Comment by kl7sn** [comment]
已在 https://github.com/shimohq/mogo/commit/732bfe75685e94bebd9a0d3f356dea8a15a6b065 提交中修复

感谢反馈，event 模块正在开发中，功能还未启用。
