### ISSUE TITLE
访问Mogo UI，输入账号密码后没有跳转仍是登录页面，刷新页面后进入Mogo页面；mogo_mock_1容器起不来

### ISSUE THREAD

**Issue by Zouxuejun** [shimohq/mogo#147]
1、访问(http://192.168.9.203:19001/user/login)，输入账号密码后没有跳转仍是登录页面，修改url为http://192.168.9.203:19001/query进入Mogo页面；
<img width="665" alt="image" src="https://user-images.githubusercontent.com/41265142/162381349-b934533b-f398-4f13-b1ea-bde3cdcb8e55.png">
2、docker-compose部署，mogo_mock_1容器起不来，实际mysql容器是起来的，数据库也初始化了；
![image](https://user-images.githubusercontent.com/41265142/162377797-0bb9cbf0-2457-4c08-9dc8-a41e0c98159e.png)
<img width="343" alt="image" src="https://user-images.githubusercontent.com/41265142/162377877-44f7595f-bf80-4155-8488-450bbfa32218.png">

**Comment by kl7sn** [comment]
没有跳转的问题已经在 master 分支修复，相关 commit: https://github.com/shimohq/mogo/commit/0ec98c2944de2466890eab4840f869c5bb038b70#diff-074ffbec94e5850c1f3dae5c9818641b7934d6063daa90013bbddcafc475462d

mogo_mock_1 容器起不来是正常现象，在完成数据 mock 后退出了，api 服务正常即可。

**Comment by sevennt** [comment]
@Zouxuejun 这个问题解决了么？

**Comment by Zouxuejun** [comment]
多谢，已经解决了 @sevennt
