### ISSUE TITLE
二进制安装-Linux AMD64 架构-default-ch加载不了问题

### ISSUE THREAD

**Issue by qinjianping** [shimohq/mogo#148]
![image](https://user-images.githubusercontent.com/36214123/162384009-593277fc-d75f-4c2d-b2ff-0f60ff7ea502.png)

**Comment by Zouxuejun** [comment]
首先要在系统管理添加实例成功，新增数据库才能选择实例

**Comment by qinjianping** [comment]
请问有没有技术讨论的群？微信？钉钉？QQ? 社区？

**Comment by kl7sn** [comment]
> 请问有没有技术讨论的群？微信？钉钉？QQ? 社区？

https://github.com/shimohq/mogo 
下方有微信二维码，扫码加我，拉你进微信群

**Comment by sevennt** [comment]
> 首先要在系统管理添加实例成功，新增数据库才能选择实例 ![image](https://user-images.githubusercontent.com/41265142/162385092-9d91e284-6179-4257-9be8-b71d401b57af.png) ![image](https://user-images.githubusercontent.com/41265142/162385150-e165a802-64a7-4086-89d5-fce9399d38f3.png)

@qinjianping 参考这个回答
