### ISSUE TITLE
文档使用说明不详细，希望能补充详细点

### ISSUE THREAD

**Issue by Zouxuejun** [shimohq/mogo#149]

**Comment by kl7sn** [comment]
文档地址 https://mogo.shimo.im/，具体哪些方面可以提下，我们这边有针对性的进行补充。

**Comment by sevennt** [comment]
@Zouxuejun 详细文档见 @kl7sn 贴的地址，如果觉得哪个地方缺失文档，可以提出来，我们再补充。

**Comment by Zouxuejun** [comment]
mogo环境是docker-compose搭建的，集群管理和mogo部署方式有关联吗？因为我是测试，所以很多都不太懂，这些配置实际是什么含义？
<img width="918" alt="image" src="https://user-images.githubusercontent.com/41265142/162657165-bd8a24ea-2b10-4fcf-a3d2-f0e91abc5ce5.png">

**Comment by sevennt** [comment]
docker-compose 只是让你快速体验一下 mogo 的完整流程。

mogo 里面的集群管理，是为了 Kubernetes 环境部署来服务的，如果你的业务都是部署在 Kubernetes 环境，那你是需要集群管理这个功能来配置集群信息的。
