### ISSUE TITLE
cannot create directory '/bitnami/kafka/config': Permission denied

### ISSUE THREAD

**Issue by ang00** [shimohq/mogo#57]
docker-compose  up fail
```shell
kafka 15:23:22.71
kafka 15:23:22.71 Welcome to the Bitnami kafka container
kafka 15:23:22.71 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
kafka 15:23:22.71 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues
kafka 15:23:22.71
kafka 15:23:22.72 INFO  ==> ** Starting Kafka setup **
kafka 15:23:22.81 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
mkdir: cannot create directory '/bitnami/kafka/config': Permission denied
```

**Comment by askuy** [comment]
> docker-compose up fail
> 
> ```shell
> kafka 15:23:22.71
> kafka 15:23:22.71 Welcome to the Bitnami kafka container
> kafka 15:23:22.71 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
> kafka 15:23:22.71 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues
> kafka 15:23:22.71
> kafka 15:23:22.72 INFO  ==> ** Starting Kafka setup **
> kafka 15:23:22.81 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
> mkdir: cannot create directory '/bitnami/kafka/config': Permission denied
> ```

solution:
1. chmod +x 777 data/kafka
2. chown -R 1001:1001 data/kafka

https://stackoverflow.com/questions/67361345/getting-error-mkdir-cannot-create-directory-bitnami-rabbitmq-permission-den

![image](https://user-images.githubusercontent.com/14119383/155280740-b28de61a-2eb4-4f3f-a8a5-e4e81ee3cf77.png)

**Comment by sevennt** [comment]
@ang00 it's fixed?
