### ISSUE TITLE
首页二维码不能扫码，显示不全。

### ISSUE THREAD

**Issue by stuartjing** [shimohq/mogo#63]
首页二维码不能扫码，显示不全。

**Comment by sevennt** [comment]
@stuartjing 切换代理，然后试试，这个是网络问题。

**Comment by stuartjing** [comment]
<img width="652" alt="image" src="https://user-images.githubusercontent.com/3454260/156283958-21ff149a-42de-4539-b3a6-bb44508f9bf1.png">
左下角右下见，二维码的定位都没显示全。

**Comment by sevennt** [comment]
嗯，这个就是网络问题，图片没显示全，直接加这个微信账号吧：MEXES_
