### ISSUE TITLE
windows下启动运行页面报404

### ISSUE THREAD

**Issue by LL1024LL** [shimohq/mogo#91]
embed包中的，文件夹分隔符采用正斜杠/,即使是windows系统也采用这个模式。
![image](https://user-images.githubusercontent.com/34938683/159424062-18234567-e650-4e8c-b1d1-f3d961ff8487.png)

![image](https://user-images.githubusercontent.com/34938683/159424609-2ff05e02-c13e-4eab-9fb1-26f3e0f82214.png)

在windows下运行，路径会拼接以为"\\"分隔符的路径形式，文件将找不到。

![image](https://user-images.githubusercontent.com/34938683/159423928-8005ed14-f951-4cde-bd29-34cd6cd945b0.png)

类似的issue: https://github.com/golang/go/issues/45230

**Comment by sevennt** [comment]
@LL1024LL 暂时不打算支持 windows，可以考虑用 windows wsl 来跑

**Comment by LL1024LL** [comment]
噢，了解了

**Comment by kl7sn** [comment]
我们对 ego 进行了升级，支持了 windows 环境下 Embed   @LL1024LL 

https://github.com/shimohq/mogo/commit/812d7d545e3528dd0c7c3c508aa485a7f2363184
