### ISSUE TITLE
queryEncode会将请求参数中带“and“的条件截断

### ISSUE THREAD

**Issue by LL1024LL** [shimohq/mogo#95]
```
// api/internal/service/inquiry/core.go
func queryEncode(in string) ([]queryItem, error) {
	res := make([]queryItem, 0)
	for _, a := range strings.Split(in, "and") {
		for _, op := range queryOperatorArr {
			if err := queryEncodeOperation(a, op, &res); err != nil {
				return nil, err
			}
		}
	}
	elog.Debug("queryEncode", elog.Any("step", "finish"), elog.Any("items", res))
	return res, nil
}
```
如果参数中包含"and"关键字，将会被截断
![image](https://user-images.githubusercontent.com/34938683/159444747-a0baf676-fff2-4c32-b9f4-8feb63b511a7.png)
前端报错：
![image](https://user-images.githubusercontent.com/34938683/159444794-7ff9e283-4ae2-4c18-a194-2e07e8b05607.png)

**Comment by kl7sn** [comment]
感谢反馈，本次提交中对相关问题进行了修复。

https://github.com/shimohq/mogo/commit/c3dafc883c0494bf94186c988898e9db3401e9c1
