### ISSUE TITLE
feat: 希望支持clickhouse导入阿里云日志系统

### ISSUE THREAD

**Issue by linthan** [shimohq/mogo#96]
1 clickhouse完全开源，可以自行搭建节约成本。 但是没有一个好用的可视化界面，查询语法的能力较阿里云日志也相对逊色一些。 
对于有特殊需求的日志数据，是否可以通过一键导入到阿里云日志系统，方便分析使用。 对于没有太多价值的日志，用clickhouse查查就可以了。

**Comment by sevennt** [comment]
这个功能对我们不是刚需，如果有这个需求，欢迎提 PR 给 mogo。或者给阿里云提工单，让他们在 SLS 上实现这个功能？

**Comment by linthan** [comment]
^_^

**Comment by askuy** [comment]
> 1 clickhouse完全开源，可以自行搭建节约成本。 但是没有一个好用的可视化界面，查询语法的能力较阿里云日志也相对逊色一些。 对于有特殊需求的日志数据，是否可以通过一键导入到阿里云日志系统，方便分析使用。 对于没有太多价值的日志，用clickhouse查查就可以了。

可以配置fluent-bit采集通道，对少量特定日志双采集到sls和clickhouse

**Comment by linthan** [comment]
> > 1 clickhouse完全开源，可以自行搭建节约成本。 但是没有一个好用的可视化界面，查询语法的能力较阿里云日志也相对逊色一些。 对于有特殊需求的日志数据，是否可以通过一键导入到阿里云日志系统，方便分析使用。 对于没有太多价值的日志，用clickhouse查查就可以了。
> 
> 可以配置fluent-bit采集通道，对少量特定日志双采集到sls和clickhouse

是一个好的思路。 这样只要控制好fluent-bit就可以解决问题了。
